<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>awswaf-captcha</name>
   <tag></tag>
   <elementGuidId>a2df0e49-220d-4f01-85b3-cf619d16225d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>awswaf-captcha</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aws-captcha']/awswaf-captcha</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>awswaf-captcha</value>
      <webElementGuid>64d92ea0-5e03-4ab5-94c5-bd2a8aea25f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>65ed76fa-ba11-433c-801b-06f15d4a985e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aws-captcha&quot;)/awswaf-captcha[1]</value>
      <webElementGuid>6df829a2-28aa-4b02-9a3a-ed87359c1b8a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aws-captcha']/awswaf-captcha</value>
      <webElementGuid>e1bf57d7-e15c-4d84-b4d0-a4a077aaba46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solving the puzzle helps us secure your transactions.'])[1]/following::awswaf-captcha[1]</value>
      <webElementGuid>66e1766f-08a3-4982-84a3-053a6496dd40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Let', &quot;'&quot;, 's solve the puzzle!')])[1]/following::awswaf-captcha[1]</value>
      <webElementGuid>02c92802-0079-446c-b8fa-63dcb43b0351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//awswaf-captcha</value>
      <webElementGuid>2ad7b370-f11d-4cc3-b0d4-ad2905c2e3a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
