<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Mr.Mrs.Ms</name>
   <tag></tag>
   <elementGuidId>bbb080e0-daa6-4f36-99f1-bcffc2765ae8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select.r-30o5oe.r-1niwhzg.r-1yadl64.r-1p0dtai.r-t1w4ow.r-ubezar.r-majxgm.r-1pi2tsx.r-1r74h94.r-135wba7.r-crgep1.r-orgf3d.r-1ny4l3l.r-10paoce.r-u8s1d.r-3mc0re.r-ipm5af.r-34rx7k.r-417010</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='adultForm0']/div/div/div[2]/div/div/div/select</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4a972bc3-774c-48ef-90dc-7ca782f38b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>r-30o5oe r-1niwhzg r-1yadl64 r-1p0dtai r-t1w4ow r-ubezar r-majxgm r-1pi2tsx r-1r74h94 r-135wba7 r-crgep1 r-orgf3d r-1ny4l3l r-10paoce r-u8s1d r-3mc0re r-ipm5af r-34rx7k r-417010</value>
      <webElementGuid>c2109015-47de-4562-b3d9-75c6fb8d2824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Mr.Mrs.Ms.</value>
      <webElementGuid>c79bc425-f1be-4e07-8c63-5a6eccb1f837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;adultForm0&quot;)/div[@class=&quot;css-1dbjc4n r-14lw9ot r-kdyh1x r-da5iq2 r-bztko3&quot;]/div[@class=&quot;css-1dbjc4n r-1ihkh82 r-bztko3&quot;]/div[@class=&quot;css-1dbjc4n r-14lw9ot&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n&quot;]/div[@class=&quot;css-1dbjc4n r-1awozwy r-18u37iz r-eu3ka r-1wtj0ep r-1ny4l3l r-10paoce r-edyy15&quot;]/select[@class=&quot;r-30o5oe r-1niwhzg r-1yadl64 r-1p0dtai r-t1w4ow r-ubezar r-majxgm r-1pi2tsx r-1r74h94 r-135wba7 r-crgep1 r-orgf3d r-1ny4l3l r-10paoce r-u8s1d r-3mc0re r-ipm5af r-34rx7k r-417010&quot;]</value>
      <webElementGuid>a3a7cd29-df7c-44c8-97f6-ca3dda9c00cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='adultForm0']/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>4ca0e620-3b89-4bfb-a4f2-9d492b15f698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::select[1]</value>
      <webElementGuid>14ced2fe-2ff5-4e30-88cc-8ab87cd5382c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[5]/preceding::select[1]</value>
      <webElementGuid>0d74f004-c3d7-4dc2-a800-56292521e396</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/div/div/div[2]/div/div/div/select</value>
      <webElementGuid>5e2b13f4-2c15-4f5f-b9f9-87c98fedf0a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[(text() = 'Mr.Mrs.Ms.' or . = 'Mr.Mrs.Ms.')]</value>
      <webElementGuid>81cd57e5-138f-4837-bac3-0c3c58f96519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
